from __future__ import annotations

from pathlib import Path

from mco.config import WorkspaceConfig, init_workspace
from mco.dashboard.static import render_dashboard
from mco.dispatch.queue import claim_dispatch, complete_dispatch, queue_dispatch
from mco.replay.ledger import register_artifact, set_workflow
from mco.task.lifecycle import create_task
from mco.workflow.templates import load_workflow_template, write_plan


def run_hello_demo(config: WorkspaceConfig) -> dict:
    init_workspace(config)
    template = load_workflow_template("hello-multi-cli")
    created = create_task(config, "Hello Multi-CLI Demo", "Run the sanitized built-in demo.")
    plan_path = write_plan(created.task_dir, template)
    set_workflow(created.task_dir, template["name"])
    dispatch = queue_dispatch(
        created.task_dir,
        "generic-cli",
        "Create demo evidence",
        "Create a small evidence artifact and complete the dispatch.",
    )
    claim_dispatch(created.task_dir, dispatch["dispatch_id"], "generic-cli")
    evidence_path = created.task_dir / "artifacts" / "demo-evidence.md"
    evidence_path.write_text(
        "# Demo Evidence\n\nThis artifact was generated by `mco demo hello-multi-cli`.\n",
        encoding="utf-8",
    )
    register_artifact(created.task_dir, evidence_path, "demo-evidence")
    complete_dispatch(created.task_dir, dispatch["dispatch_id"], "generic-cli", "Demo evidence generated.")
    dashboard_path = render_dashboard(config, created.task_id)
    return {
        "task_id": created.task_id,
        "task_dir": str(created.task_dir),
        "plan": str(plan_path),
        "evidence": str(evidence_path),
        "dashboard": str(dashboard_path),
    }
