from __future__ import annotations

import json
from pathlib import Path

from mco.adapters.scaffold import scaffold_adapter
from mco.config import WorkspaceConfig
from mco.demo.hello import run_hello_demo
from mco.replay.readout import render_replay_html, replay_ledger


def run_walkthrough_demo(config: WorkspaceConfig, output_dir: Path) -> dict:
    output_dir = output_dir.expanduser().resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    hello = run_hello_demo(config)
    task_dir = Path(hello["task_dir"])
    ledger_path = task_dir / "RUN_LEDGER.json"
    replay_path = output_dir / "RUN_REPLAY.txt"
    replay_path.write_text(replay_ledger(ledger_path), encoding="utf-8")
    replay_html_path = render_replay_html(ledger_path, output_dir / "RUN_REPLAY.html")

    adapter_kit_dir = output_dir / "adapter-kit-demo-cli"
    adapter = scaffold_adapter("demo-cli", adapter_kit_dir, force=True)

    readme_path = output_dir / "README.md"
    readme_path.write_text(
        "\n".join(
            [
                "# Multi-CLI Orchestrator Walkthrough",
                "",
                "This directory was generated by `mco demo walkthrough`.",
                "",
                "## What Was Created",
                "",
                f"- Demo task: `{hello['task_id']}`",
                f"- Task directory: `{hello['task_dir']}`",
                f"- Dashboard: `{hello['dashboard']}`",
                f"- Replay transcript: `{replay_path}`",
                f"- Replay HTML: `{replay_html_path}`",
                f"- Adapter kit: `{adapter_kit_dir}`",
                "",
                "## Inspect",
                "",
                "```bash",
                f"mco run replay {ledger_path}",
                f"python {adapter_kit_dir / 'test_demo_cli_adapter_contract.py'}",
                "```",
                "",
                "The adapter kit starts disabled and uses a deterministic fake CLI fixture. This is intentional: new CLI integrations need evidence before promotion.",
                "",
            ]
        ),
        encoding="utf-8",
    )

    result = {
        "schema": "mco.demo_walkthrough.v1.0",
        "task_id": hello["task_id"],
        "task_dir": hello["task_dir"],
        "dashboard": hello["dashboard"],
        "run_replay": str(replay_path),
        "run_replay_html": str(replay_html_path),
        "adapter_kit": str(adapter_kit_dir),
        "adapter_files": adapter["files"],
        "readme": str(readme_path),
    }
    (output_dir / "walkthrough.json").write_text(json.dumps(result, indent=2) + "\n", encoding="utf-8")
    result["summary"] = str(output_dir / "walkthrough.json")
    return result
